### PR TITLE
fix to signal warning when host dead.

### PR DESCRIPTION
**Pull request by hyotang666**

### CODE REVIEW

**Comment by mihaiolteanu** [comment]
Please describe a scenario where the current implementation fails and how this PR fixes it.

**Comment by hyotang666** [comment]
Oh, sorry for fewer words.

It seems that the host www.metrolyrics.com is dead.

```lisp
(find-lyrics (find 'metrolyrics *websites* :key #'website-name) "metallica" "hit the light")

debugger invoked on a USOCKET:NS-HOST-NOT-FOUND-ERROR in thread
#<THREAD "main thread" RUNNING {1001550733}>:
  Condition USOCKET:NS-HOST-NOT-FOUND-ERROR was signalled.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(USOCKET::HANDLE-CONDITION #<SB-BSD-SOCKETS:HOST-NOT-FOUND-ERROR {10039276E3}> NIL "www.metrolyrics.com")
   source: (ERROR USOCK-ERROR :SOCKET SOCKET :HOST-OR-IP HOST-OR-IP)
```

Other hosts are alive.
In such cases, to signal warning is better rather than USOCKET:NS-HOST-NOT-FOUND-ERROR.

**Comment by mihaiolteanu** [comment]
Yes, metrolyrics seems to be dead from what I see.
Shouldn't we then remove it from the list of supported websites instead?

**Comment by hyotang666** [comment]
I see.

But any supported websites may die in the future.
With this PR, even if in such situations find-lyrics will work fine.
End-user never cares about *websites*. (additionally *websites* is internal.)

**Comment by mihaiolteanu** [comment]
Yes, that is true. Good point!

If a website is dead forever, though, does it make sense to keep it?
I agree that we don't know if this is the case for us here.

`find-lyrics` is called from `lyrics`, which goes through the whole list of supported websites until it finds a match.
What happens when it gets to a dead website (metrolyrics, in this case)?
Does it go to the next one, or does it stop with an error?

**Comment by hyotang666** [comment]
> What happens when it gets to a dead website (metrolyrics, in this case)?
> Does it go to the next one, or does it stop with an error?

LYRICS does not handle any error so
the debugger is invoked without restarts even if any alive hosts remain in the list.

**Comment by mihaiolteanu** [comment]
So you PR does not handle that case?

**Comment by hyotang666** [comment]
Without this PR, LYRICS does not handle any errors and FIND-LYRICS invokes debugger.

With this PR, FIND-LYRICS warning instead of invoking debugger and returns NIL, so LYRICS can go next.

**Pull request merged**
